### ISSUE TITLE
MunkiReportPackager: "AttributeError: module 'FoundationPlist' has no attribute 'readPlist'"

### ISSUE THREAD

**Issue by henningkessler** [autopkg/munkireport-recipes#6]
Hi, after installing AutoPkg 2.0.2 I am getting this this error after running munkireport.munki:
```
admin@somehost[10:50][~]: autopkg run -v munkireport.munki
Processing munkireport.munki...
StopProcessingIf
StopProcessingIf: (BASEURL == "https://munki.example.com:8888") is False
MunkiReportUrlCreator
MunkiReportUrlCreator: Found URL http://mr.int.somehost.de/index.php?/install/modules
URLDownloader
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/admin/Library/AutoPkg/Cache/local.munki.munkireport/downloads/munkireportpackager.sh
MunkiReportPackager
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 480, in process
    self.main()
  File "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.munkireport-recipes/MunkiReportPackager.py", line 95, in main
    result = FoundationPlist.readPlist(resultplist)
AttributeError: module 'FoundationPlist' has no attribute 'readPlist'
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
module 'FoundationPlist' has no attribute 'readPlist'
Failed.
Receipt written to /Users/admin/Library/AutoPkg/Cache/local.munki.munkireport/receipts/munkireport-receipt-20200207-105124.plist

The following recipes failed:
    munkireport.munki
        Error in local.munki.munkireport: Processor: MunkiReportPackager: Error: module 'FoundationPlist' has no attribute 'readPlist'

Nothing downloaded, packaged or imported.
```

**Comment by henningkessler** [comment]
Fixed.
